### ISSUE TITLE
GH Action fails to install uv after the release of version 0.5.0

### ISSUE THREAD

**Issue by jessanmen1** [Titan-Systems/titan-core-action#10]
# Context
We are using the GH Action as part of our CICD pipeline. A few hours ago, it started failing with the following error:

```
  0.165 /bin/sh: 1: /root/.cargo/bin/uv: not found
  ------
  Dockerfile:10
  --------------------
     8 |     COPY requirements.txt /requirements.txt
     9 |     
    10 | >>> RUN /root/.cargo/bin/uv pip install --system --no-cache -r requirements.txt
    11 |     
    12 |     COPY main.py /main.py
  --------------------
  ERROR: failed to solve: process "/bin/sh -c /root/.cargo/bin/uv pip install --system --no-cache -r requirements.txt" did not complete successfully: exit code: 127
Error: Docker build failed with exit code 1
```

# Root cause investigation
I could reproduce the error by building the docker locally. As the error states, it's related to uv, so I checked that there was a new uv version (0.5.0).
I compared the installers for the 0.4.30 and 0.5.0 versions and found the root cause:
![image](https://github.com/user-attachments/assets/16d31e9d-a0c6-4ff0-965d-877807ea2fd5)

Now, uv is installed under the `.local` directory instead of the `.cargo` one.  

I tried again to build the image by changing the directory, and it worked.

# Possible solutions
1. Pin the uv version so changes upstream won't break the GH Action
2. Change `.cargo` dir to `.local`

I like Option 1) more because it gives you more control.

**Comment by teej** [comment]
Confirmed this works again after merging #11

**Comment by teej** [comment]
Thank you for the report & PR!
