### ISSUE TITLE
Add `.titanignore` functionality

### ISSUE THREAD

**Issue by GClunies** [Titan-Systems/titan-core-action#5]
I have an `infra/snowflake/` folder to manage Snowflake IaC using titan. For local development, I have a conda `environment.yml` file to define my virtual python env. Unfortunately, when I try to use the `titan-core-action` it thinks the `environment.yml` file is a titan config because it [grabs all YAML files](https://github.com/Titan-Systems/titan-core-action/blob/34db0cf0dc7cfbda451f34bdb49367ada4834784/main.py#L25) under the `resource-path:` config. I'd like some simple way to exclude files/folders from titan when it runs. I imagine something like a `.titanignore` (similar to dbt's `.dbtignore`).

Screenshot illustrating the folder structure I have.
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/1e60ab3d-ea70-4024-995b-a058f7fc0972">

For now, I could:
1. Move the `environment.yml` file outside my `infra/snowflake/` folder so the only YAMLs are titan configs. This makes it less clear what the conda env is actually being used for.
2. Nest my `databases/`, `roles/` etc folders in a parent `resources/` folder. FWIW, this feels like unnecessary nesting.

**Comment by teej** [comment]
This should be easy to do

**Comment by teej** [comment]
Added on `main`
